name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch: # Allow manual triggering of the workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-unit:
    if: ${{ github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false # Continue jobs even if any of the jobs fail
    env:
      NODE_ENV: development

    steps:
      - name: 📥 Check out the repository code
        uses: actions/checkout@v4

      # OPTIONAL STEP IF YOU WANT TO USE NODE AS RUNTIME
      #   - name: Use Node.js ${{ matrix.node-version }}
      #     uses: actions/setup-node@v4
      #     with:
      #       node-version: ${{ matrix.node-version }}

      - name: 🥟 Set up Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: ⬇️ Install dependencies
        run: bun install --frozen-lockfile

      - name: 🧪 Run unit test
        run: bun run test:unit
